### PR TITLE
Add start point attribute

### PR DESCRIPTION
**Pull request by mIbrahim017**
client can determine from where the progress can start , top , left ,
bottom , right

### CODE REVIEW

**Comment by xiprox** [comment]
Hello, thank you for the contribution. A few things though:
- Would you mind renaming the `startPoint` field to `mStartPoint`? (See <a href="https://source.android.com/source/code-style.html#java-style-rules">Field Naming Conventions</a>)
- Can you make the enums all lower case? It's more consistent that way. (See <a href="http://developer.android.com/reference/android/widget/LinearLayout.html#attr_android:gravity">`android:gravity`</a> or <a href="http://developer.android.com/reference/android/widget/LinearLayout.html#attr_android:orientation">`android:orientation`</a> for some examples.)
- Can you remove the `mv_mark` value change (from `3` to `1`) from the PR. If there is a reason for the change, I can merge it in another PR.

Sorry for being so picky. :smiley:

**Comment by mIbrahim017** [comment]
yeah , you are right :+1:  i commit the changes

**Comment by xiprox** [comment]
Thanks again. :+1:

**Comment by mIbrahim017** [comment]
you welcome :+1: :smile:

**Comment by xiprox** [comment]
I've pushed a new (`1.1.0`) version to maven which includes this change. Good luck!

**Pull request merged**
